### ISSUE TITLE
Really target folder uploaded?

### ISSUE THREAD

**Issue by vsaldanyac** [NanowarOfSteel/HelloWorld#11]
I can't understand why target folder is updated....

But we can forget if the band comes back again to Spain (Bcn) 😉

**Comment by mattiamari** [comment]
Addressed by #9

**Comment by NanowarOfSteel** [comment]
We merged the issue, fixing the .gitignore and deleting the /target folder. Sorry for the noob error.
Thanks!

**Comment by vsaldanyac** [comment]
You are the best!!!
