### ISSUE TITLE
Store it in a WAR file - Make a NanoWAR file happen

### ISSUE THREAD

**Issue by rzo1** [NanowarOfSteel/HelloWorld#19]
You could even store it in a WAR (Web Application Archive) to create an actual nano.war file :-)

EDIT: Looks like @borjabravo9426 on YouTube already had the same idea, so quoting:

> you can store a Helloworld app in a java war file. This will be the smallest war file and you would be able to say that it would be ... a nano war file

**Comment by tandraschko** [comment]
:D :D :D

**Comment by alfredogangemi** [comment]
#22

**Comment by MacKaiserDev** [comment]
i recommend to write the source code for the content of the .war file in Nano.

**Comment by rzo1** [comment]
Yeah - we are fixed with #22
