### ISSUE TITLE
[Feature Request] Release a Single of this, please

### ISSUE THREAD

**Issue by vorant94** [NanowarOfSteel/HelloWorld#41]
i'm a little bit of perfectionist and usually buy songs with full albums. its the first song of you that i found and i really liked it, i would like to buy it on iTunes, but i don't really need the full album tbh...

**Comment by NanowarOfSteel** [comment]
Unfortunately the song is part of the record, and we cannot change this. However, if you are going to take the full record, we hope you will enjoy the other songs as well.
